---
- hosts: localhost
  ignore_errors: yes
  connection: localhost
  gather_facts: False
  vars:
    region: eu-west-1
    count: 1
  vars_files:
    - ansible_vars.yml
  tasks:

#Meraki info gathering first

    - name: GET UPLINK IP
      uri:
        url: https://api.meraki.com/api/v1/organizations/265528/appliance/uplink/statuses
        method: GET
        headers:
          Content-Type: application/json
          Accept: application/json
          X-Cisco-Meraki-API-Key: "{{merakiapikey}}"
        return_content: true
        follow_redirects: all
        validate_certs: true
      register: meraki_uplink
        
    - name: GET Appliance Subnets
      uri:
        url: https://api.meraki.com/api/v1/devices/Q2NY-UYYZ-XVLK/appliance/dhcp/subnets
        method: GET
        headers:
          Content-Type: application/json
          Accept: application/json
          X-Cisco-Meraki-API-Key: "{{merakiapikey}}"
        return_content: true
        follow_redirects: all
        validate_certs: true
      register: meraki_subnets

# AWS part
    - ec2_vpc_net_info:
      register: vpc_ids

    - name: Create a new vgw attached to a specific VPC
      ec2_vpc_vgw:
        state: present
        region: eu-west-1
        vpc_id: "{{vpc_ids.vpcs.0.vpc_id}}"
        name: Ansible-VGW
        type: ipsec.1
      register: created_vgw

    - name: Propoage routes from the newly created VGW
      ec2_vpc_route_table:
        vpc_id: "{{vpc_ids.vpcs.0.vpc_id}}"
        route_table_id: "{{rtid}}"
        state: present
        propagating_vgw_ids: "{{created_vgw.vgw.id}}"
        subnets: subnet-98dea0d0
      register: route_table

    - name: Create Customer Gateway
      ec2_customer_gateway:
        bgp_asn: 12345
        ip_address: "{{meraki_uplink.json.1.uplinks.0.publicIp}}"
        name: Ansible_Meraki_MX
        region: eu-west-1
      register: cgw 

    - name: GET CGW_ID
      set_fact:
        cgw_id: "{{cgw.gateway.customer_gateway.customer_gateway_id}}"

    - name: create a VPN connection
      ec2_vpc_vpn:
        state: present
        static_only: true
        vpn_gateway_id: "{{created_vgw.vgw.id}}"
        customer_gateway_id: "{{cgw.gateway.customer_gateway.customer_gateway_id}}"
        tunnel_options: 
          -
            PreSharedKey: "{{psk}}"
          -
            PreSharedKey: "{{psk}}"
        routes:
          - "{{meraki_subnets.json.0.subnet}}"
      register: vpn


#set up meraki VPN 
    - name: SET third party VPN
      uri:
        url: https://api.meraki.com/api/v1/organizations/265528/appliance/vpn/thirdPartyVPNPeers
        method: PUT
        headers:
          Content-Type: application/json
          Accept: application/json
          X-Cisco-Meraki-API-Key: "{{merakiapikey}}"
        return_content: true
        follow_redirects: all
        validate_certs: true
        body_format: json
        body: { "peers": [ {  "name": "AWS_Peer",
            "publicIp": "{{vpn.vgw_telemetry.0.outside_ip_address}}" ,
            "privateSubnets": [
                "{{vpc_ids.vpcs.0.cidr_block}}",
            ],
            "secret": "{{psk}}",
            "networkTags": [ "all" ],
            "ikeVersion": "1",
            "ipsecPoliciesPreset": "aws"}
        ]
        }
